name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install yarn
        run: |
          npm install -g yarn
          yarn --version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test index.test.tsx --watchAll=false

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Debug: List Android Directory
        run: ls -la android/

      - name: Generate Android files
        run: |
          yarn add -D @expo/cli
          yarn expo prebuild -p android --no-install

      - name: Build Android APK
        run: eas build --platform android --profile preview --non-interactive --no-wait

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            android
            .expo
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build- 